# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

export HTTP_PROXY=http://proxy.server.com:80
export HTTPS_PROXY=http://proxy.server.com:80

source .alias

